title: Khasanov's Blog
author:
  name: Rakhmatjon Khasanov
  email: r.khasanov97@gmail.com

description: >
  Welcome to my blog – a space where I share insights on software development,
  lifelong learning, productivity, and personal growth. From coding tutorials
  and tech reviews to reflections on language learning and everyday challenges,
  this blog is dedicated to helping curious minds grow with clarity, consistency,
  and creativity.

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
  quiet_deps: true
  silence_deprecations: [import]


nav:
  - name: "About"
    link: "https://khasanovr.github.io"

minima:
#   Minima skin selection. Available skins are:
#     * classic            Default, light color scheme.
#     * dark               Dark variant of the classic skin.
#     * auto               Adaptive skin based on the classic and dark skins.
#     * solarized-light    Light variant of solarized color scheme.
#     * solarized-dark     Dark variant of solarized color scheme.
#     * solarized          Adaptive skin for solarized color scheme skins.
   skin: classic

#   Set to `true` to show excerpts on the homepage.
   show_excerpts: true

#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
#   date_format: "%b-%d-%Y"

#   Social Media Links.
#     Renders icons via Font Awesome Free webfonts CDN, based on ordered list of
#     entries. Valid entry keys:
#       * title    Tooltip rendered on hovering over icon.
#       * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
#       * url      Full URL of social profile.
   social_links:
     - title: Rakhmatjon Khasanov
       icon: telegram
       url: "https://t.me/Rakhmatjon_Khasanov"
     - title: Rakhmatjon Khasanov
       icon: github
       url: "https://github.com/KhasanovR"
     - title: Rakhmatjon Khasanov
       icon: linkedin
       url: "https://www.linkedin.com/in/rakhmatjon-khasanov"
